name: Build and Release Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build-deb.sh executable
        run: chmod +x ./build-deb.sh

      - name: Build and Release Debian Package
        run: ./build-deb.sh

      - name: Copy deb files to artifact directory
      run: |
        mkdir -p artifacts
        cp ./src/*.deb artifacts/

      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: deb
          path: artifacts/

  release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Download deb artifacts
      uses: actions/download-artifact@v3
      with:
        name: deb
        path: artifacts

    - name: Create GitHub Release
      id: create_release
      run: |
        file_path=$(ls artifacts/*.deb | head -n1)
        filename=$(basename "$file_path")
        package_name=$(echo "$filename" | cut -d_ -f1)
        version=$(echo "$filename" | cut -d_ -f2)
        date=$(date "+%Y-%m-%d %H:%M:%S")
        gh release create "$package_name $version" artifacts/*.deb -t "ReleaseTitle: $package_name $version" -n "Released on $date"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
